client/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="home"),
    url(r'^login/$', views.fb_login, name="login"),
    url(r'^payment_sample/$', views.paypal_sample, name="paypal_sample"),
    url(r'^games/$', views.games, name="games"),
    url(r'^games/(?P<game_id>[0-9]+)/$', views.bet, name="bet"),
    url(r'^register/$', views.registration, name="registration"),
    #url(r'^client/(?P<client_id>[0-9]+)/$', views.client_transactions, name="client_transactions"),
    url(r'^screen/$', views.screen_size)
]

hq/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.home, name="home"),
    url(r'^staff/$', views.staff_activity, name="staff_activity"),
    url(r'^staff/create/$', views.create_staff, name="create_staff"),
    url(r'^games/$', views.games, name="games"),
    url(r'^score/create/$', views.create_score, name="score_game"),
    url(r'^services/credit/$', views.service_credit, name="service_credit"),
]

luckyending/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('client.urls', namespace='client')),
    url(r'^hq/', include('hq.urls', namespace='hq')),
    url(r'^logout/$', logout, name='logout'),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
]

client/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator
from hq.models import Game

# Create your models here.

class Client(models.Model):
    user = models.OneToOneField(User)
    fb_id = models.CharField(max_length=64, blank=True, null=True)
    first_name = models.CharField(max_length=32)
    last_name = models.CharField(max_length=16)
    contact_number = models.CharField(max_length=12)

    def __str__(self):
        return str(self.user.email)

class Transaction(models.Model):
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    client = models.ForeignKey(Client)
    wallet = models.PositiveIntegerField(default=0)
    free_credits = models.PositiveIntegerField(default=0)
    METHOD_CHOICES = (
        ('C', 'Credit'),
        ('D', 'Debit'),
    )
    method = models.CharField(
        max_length=1,
        choices=METHOD_CHOICES,
        default='C',
    )
    METHOD_TYPE_CHOICES = (
        ('SC', 'Service'),
        ('RC', 'Regular'),
        ('GC', 'Game'),
        ('BD', 'Bet'),
        ('CD', 'Cashout')
    )
    method_type = models.CharField(
        max_length=2,
        choices=METHOD_TYPE_CHOICES,
        default='RC',
    )

    def __str__(self):
        s = {'SC': 'SC for Client '+str(self.client.id), 'RC': 'RC for Client '+str(self.client.id), 'GC': 'GC for Client '+str(self.client.id), 'BD': 'Bet/s by Client '+str(self.client.id), 'CD': 'Cashout by Client '+str(self.client.id) }[self.method_type]
        return str(s)

class ServiceCredit(Transaction):
    staff = models.ForeignKey(User, blank=True, null=True)
    SERVICE_TYPE_CHOICES = (
        ('W', 'Welcome Credits'),
        ('P', 'Promo'),
        ('R', 'Referral'),
    )
    service_type = models.CharField(
        max_length=1,
        choices=SERVICE_TYPE_CHOICES,
        default='W',
    )
    details = models.CharField(max_length=64, blank=True, null=True)

class RegularCredit(Transaction):
    SOURCE_CHOICES = (
        ('P', 'Paypal'),
        ('O', 'Others'),
    )
    source = models.CharField(
        max_length=1,
        choices=SOURCE_CHOICES,
        default='W',
    )
    reference = models.CharField(max_length=32)

class GameCredit(Transaction):
    game = models.ForeignKey(Game)
    TRIGGER_CHOICES = (
        ('W', 'Win'),
        ('R', 'Refund'),
    )
    trigger = models.CharField(
        max_length=1,
        choices=TRIGGER_CHOICES,
        default='W',
    )

class Bet(models.Model):
    game = models.ForeignKey(Game)
    client = models.ForeignKey(Client)
    ending_a = models.PositiveIntegerField(validators=[MaxValueValidator(9),])
    ending_b = models.PositiveIntegerField(validators=[MaxValueValidator(9),])
    amount = models.PositiveIntegerField()
    transaction = models.ForeignKey(Transaction, blank=True, null=True)

class Cashout(Transaction):
    STATUS_CHOICES = (
        ('Pe', 'Pending Review'),
        ('Pr', 'Processing'),
        ('Re', 'Released'),
    )
    status = models.CharField(
        max_length=2,
        choices=STATUS_CHOICES,
        default='Pe',
    )
    staff = models.ForeignKey(User, blank=True, null=True)
    reference = models.CharField(max_length=32, blank=True, null=True)
    ACCOUNT_TYPE_CHOICES = (
        ('PPL', 'Paypal'),
        ('BPI', 'BPI'),
        ('BDO', 'BDO'),
    )
    account_type = models.CharField(
        max_length=3,
        choices=ACCOUNT_TYPE_CHOICES,
        default='PPL',
    )
    account_details =models.TextField()

client/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

from django.core.validators import RegexValidator, EmailValidator

from django.core.exceptions import ValidationError

def new_username(username):
    try:
        user = User.objects.get(username=username)
    except User.DoesNotExist:
        user = None
    if user: # check if any object exists
        raise ValidationError('Email address is already registered.') 

class UserCreateForm(UserCreationForm):
    email = forms.CharField(validators=[EmailValidator, new_username])

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2', 'email']

class ClientCreateForm(forms.ModelForm):
    contact_number = forms.CharField(validators=[RegexValidator(r'^[0-9]{12}', 'Enter a valid number.')])

    class Meta:
        model = Client
        exclude = ['user']

client/views.py
import uuid

from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from paypal.standard.forms import PayPalPaymentsForm

from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse  # 1.10
# from django.core.urlresolvers import reverse #1.9

from django.contrib.auth.models import User
from django.db.models import Sum

from datetime import datetime
from django.utils import timezone

from .models import *
from .forms import *

from hq.models import Game

import hashlib

# Create your views here.
import logging

LOGGER = logging.getLogger(__name__)


def get_client_info(client_id):
    client = get_object_or_404(Client, pk=client_id)
    wallet_pos = Transaction.objects.filter(client=client, method='C').aggregate(Sum('wallet'))['wallet__sum']
    free_credits_pos = Transaction.objects.filter(client=client, method='C').aggregate(Sum('free_credits'))[
        'free_credits__sum']
    wallet_neg = Transaction.objects.filter(client=client, method='D').aggregate(Sum('wallet'))['wallet__sum']
    free_credits_neg = Transaction.objects.filter(client=client, method='D').aggregate(Sum('free_credits'))[
        'free_credits__sum']

    if wallet_pos is None or wallet_neg is None:
        wallet = 0
    else:
        wallet = wallet_pos - wallet_neg
    if free_credits_pos is None or free_credits_neg is None:
        free_credits = 0
    else:
        free_credits = free_credits_pos - free_credits_neg

    return {'client': client, 'wallet': wallet, 'free_credits': free_credits}

def client_transactions(request, client_id):
    client = get_object_or_404(Client, pk=client_id)
    transactions = Transaction.objects.filter(client=client).order_by('-id')
    return render(request, 'client/transactions.html', {'transactions': transactions})


def index(request):
    print("LANDING PAGE", request)
    return render(request, 'client/index.html', {})


def fb_login(request):
    form = AuthenticationForm()

    if request.method == 'POST':
        facebook = request.POST.get('facebook')

        if facebook:
            try:
                this_user = Client.objects.get(fb_id=str(request.POST.get('fb_id'))).user

            except Exception as e:
                fb_details = {
                    "id": str(request.POST.get('fb_id')),
                    "email": str(request.POST.get('fb_email')),
                    "first_name": str(request.POST.get('fb_first_name')),
                    "last_name": str(request.POST.get('fb_last_name')),
                }
                request.session['facebook'] = fb_details
                return HttpResponseRedirect(reverse('client:registration'))

        else:
            form = AuthenticationForm(data=request.POST)
            this_user = None

            if form.is_valid():
                this_user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password'])
            else:
                return render(request, 'client/login.html', {"form": form})

        if this_user is not None:
            login(request, this_user)
            print('next:', request.POST.get('next'))
            if request.POST.get('next'):
                return redirect(request.POST.get('next'))
            elif this_user.is_staff:
                return redirect('hq:games')
            return redirect('client:home')

    else:
        form = AuthenticationForm()

    return render(request, 'client/login.html', {"form": form})


def hash_facebook_id(instance):
    salt = 'randomizing passwords for facebook users'
    hash = hashlib.md5((str(instance) + salt).encode('utf-8')).hexdigest()
    return str(hash)


def registration(request):
    facebook = None
    post = {}

    try:
        facebook = request.session.get('facebook')
        del request.session['facebook']
    except Exception as e:
        pass

    if request.method == 'POST':
        get = False
        via_facebook = request.POST.get('facebook') == 'True'

        client_form = ClientCreateForm(request.POST)
        user_form = UserCreateForm(request.POST)

        if via_facebook:
            facebook = {
                "id": str(request.POST.get('fb_id')),
                "email": str(request.POST.get('fb_email')),
                "first_name": str(request.POST.get('fb_first_name')),
                "last_name": str(request.POST.get('fb_last_name')),
            }

        if user_form.is_valid() and client_form.is_valid():

            password = user_form.cleaned_data['password1']

            if via_facebook:
                password = hash_facebook_id(str(request.POST.get('fb_id')))

            this_user = User.objects.create_user(username=user_form.cleaned_data['email'],
                                                 email=user_form.cleaned_data['email'], password=password)
            this_user.save()

            new_client = Client(user=this_user)
            client_form = ClientCreateForm(request.POST, instance=new_client)
            this_client = client_form.save()

            login(request, this_user)

            return HttpResponseRedirect(reverse('client:home'))

        try:
            post['username'] = user_form.cleaned_data['username']
        except Exception as e:
            pass
        try:
            post['email'] = user_form.cleaned_data['email']
        except Exception as e:
            pass
        try:
            post['first_name'] = client_form.cleaned_data['first_name']
        except Exception as e:
            pass
        try:
            post['last_name'] = client_form.cleaned_data['last_name']
        except Exception as e:
            pass
        try:
            post['contact_number'] = client_form.cleaned_data['contact_number']
        except Exception as e:
            pass


    else:
        user_form = UserCreateForm()
        client_form = ClientCreateForm()
        get = True

    return render(request, 'client/registration.html',
                  {"user_form": user_form, "client_form": client_form, "facebook": facebook,
                   "get": (request.method == 'GET'), "post": post})

def paypal_sample(request):
    # What you want the button to do.
    print(reverse('paypal-ipn'))
    LOGGER.info("Derp")
    paypal_dict = {
        "business": "ivanajoyce.c-facilitator@gmail.com",
        "amount": "100.00",
        "currency_code": " PHP",
        "item_name": "LuckyEnding credits",
        "invoice": str(uuid.uuid4()),
        # "notify_url": "http://requestb.in/s319yus3",

        "notify_url": "http://jinjjabread.com" + reverse('paypal-ipn'),
        "return_url": "http://jinjjabread.com/paypal_sample?status=return",
        "success_url": "http://jinjjabread.com/paypal_sample?status=success",
        "cancel_return": "http://jinjjabread.com/paypal_sample?status=cancel",
        "custom": "Upgrade all users!",  # Custom command to correlate to some function later (optional)
    }
    client_info = get_client_info(client_id=request.user.client.id)
    form = PayPalPaymentsForm(initial=paypal_dict)

    client = get_object_or_404(Client, pk=request.user.client.id)
    transactions = Transaction.objects.filter(client=client).order_by('-id')

    context = {"form": form, "client_info": client_info, "transactions": transactions}

    return render(request, "client/paypal.html", context)


def games(request):
    games = Game.objects.all().order_by('-id')
    client_info = get_client_info(client_id=request.user.client.id)
    credits = client_info['wallet'] + client_info['free_credits']
    return render(request, 'client/games.html', {'games': games, 'today': timezone.now, 'credits': credits })

def bet(request, game_id):
    game = get_object_or_404(Game, pk=game_id)
    client_info = get_client_info(client_id=request.user.client.id)
    credits = client_info['wallet'] + client_info['free_credits']

    return render(request, 'client/bet.html', {'game': game, 'credits': credits})

def screen_size(request):
    return render(request, 'client/screen.html', {})

client/templates/client/games.html
<!--<object type="text/html" data="https://hk1-broadcast.officeapps.live.com/m/Broadcast.aspx?Fi=281d5877945a2956_4839c3b4-ab15-4cf0-a311-9ec44b505f79%2Epptx" style="height: 500px; width: 800px;">
</object>-->

{% extends 'client/base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/client/forms.css' %}">
<style>
body { color: white; font-family: Open Sans; }
hr {
    margin: 0.75em 0 1.5em 0;
    border-width: 0.2em;
    width: 110%;
    position: relative;
    left: -5%;
}
.heading {
  font-family: Open Sans;
  font-weight: 900;
  letter-spacing: 0.05em;
  color: white;
}
.orange-button {
    font-size: 0.75em;
    padding: 0.75em 2.25em;
}
.gray-button {
    font-size: 0.75em;
    padding: 0.75em 2.25em;
}
.nopadding { padding: 0 !important; }
.cashout { padding: 0.75em 0.5em; }
#free-play { letter-spacing: 0.04em; }

h1 {
    font-family: Montserrat;
    font-weight: 900;
    letter-spacing: 0.07em;
    font-size: 3em;
}

h5 {
    font-family: Montserrat;
    font-weight: 900;
    letter-spacing: 0.1em;
}

h2 { margin: 0; }

.game-top {
    width: 100%;
    height: 6em;
    color: black;
    margin: 0;
    margin-top: 1em;
    background-color: white;
    border-top-left-radius: 1em;
    border-top-right-radius: 1em;
    padding: 1.5em 0 1em 0;
    font-family: Montserrat;
}

.game-bottom {
    width: 100%;
    margin: 0;
    border-radius: 1em;
    
}
.time-left {
    background-color: red;
    border-bottom-left-radius: 1em;
    height: 3em;
}

.time-left > .row > .text {
    font-size: 0.75em;
    margin: 0;
    padding: 0 1em;
    font-weight: 700;
}

.time-left > .row > .time {
    padding: 0.4em;
    font-size: 1.4em;
    font-weight: 900;
    letter-spacing: 0.05em;
}

.status {
    background-color: #F08121;
    border-bottom-right-radius: 1em;
    height: 3em;
    text-align: center;
    display: inline-block;
    position: relative;
    vertical-align: middle;
    line-height: 3em;
    font-weight: 700;
    letter-spacing: 0.03em;
    color: white;
}

.status:hover {
    color: white;
    text-decoration: none;
}

.status:focus {
    color: white;
    text-decoration: none;
}

.schedule {
    color: #aaa;
    font-size: 0.9em;
}

.team {
    color: #444;
}
</style>
{% endblock %}

{% block content %}
<div class="row flexbox-container">
    <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2">
        <h6>PLAYING<br>
        CREDITS</h6>
    </div>
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
        <h2>PhP {{ credits }}</h2>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
        <a class="btn btn-sm btn-default" href="{% url 'client:paypal_sample' %}">VIEW WALLET</a>
    </div>
</div>
<hr>
<center>
<h1><b>EARN & PLAY</b></h1>
<h5>EARN FREE CREDITS WHILE PLAYING</h5>
<br>
<a class="btn btn-default">LEARN MORE</a>
</center>
</div>

<br>

<div style="width:100%;height:5px;background-image:url(/static/img/client/bar0.png);background-size: 100vw auto; background-repeat: no-repeat;">
</div>
<div style="background-color: black;">
<br>
<div class="container">
    {% for game in games %}
    <div class="game">
        <div class="row game-top">
            <div class="col-md-4 col-sm-4 col-xs-4 schedule">
                {{ game.schedule|date:"m-d-Y" }}<br>
                {{ game.schedule|time:"H:i" }}
            </div>
            <div class="col-md-8 col-sm-8 col-xs-8 team">
                {{ game.team_a }}<br>
                {{ game.team_b }}
            </div>
        </div>
        <div class="row game-bottom">
            <div class="col-md-8 col-sm-8 col-xs-8 time-left">
                <div class="row flexbox-container">
                    <div class="col-md-5 col-sm-5 col-xs-5 text">BETTING ENDS</div>
                    <div class="col-md-7 col-sm-7 col-xs-7 time">{{ game.status.time_left }}</div>
                </div>
            </div>
            {% if game.status.description == 'OPEN' %}<a class="col-md-4 col-sm-4 col-xs-4 status" href="#">PLACE BETS</a>
            {% else %}<a class="col-md-4 col-sm-4 col-xs-4 status" href="#">CLOSED</a>{% endif %}
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

client/templates/client/navigation.html
{% load static %}

<link rel="stylesheet" href="{% static 'css/client/forms.css' %}">
<link rel="stylesheet" href="{% static 'css/client/login.css' %}">
<script src="{% static 'js/client/login.js' %}"></script>

<div id="menu" class="sidenav">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()"><span class="glyphicon glyphicon-menu-hamburger glyphicon-lg white"></a>
  {% if user.is_anonymous %}
  <center><button onclick="changeLoginState();" class="btn btn-primary facebook">Login with Facebook</button>
  </center>

  <a href="{% url 'client:login' %}">Login</a>
  <a href="{% url 'client:registration' %}">Registration</a>
  {% else %}
  <a href="{% url 'client:home' %}">Home</a>
  <a href="{% url 'client:games' %}">Games</a>
  <a href="#">Current Bets*</a>
  <a href="{% url 'client:paypal_sample' %}">My Wallet</a>
  {% endif %}
  <hr style="display: block; height: 1px; border-top: 1px solid #ccc; margin: 1em 1em; padding: 0; ">
  <a href="{% url 'client:home' %}#howto">How to Play</a>
  <a href="#">About Lucky Ending*</a>
  {% if not user.is_anonymous %}
  <hr style="display: block; height: 1px; border-top: 1px solid #ccc; margin: 1em 1em; padding: 0; ">
  <a href="#">Logout*</a>
  {% endif %}
</div>

<div class="flex-navigation navbar-fixed-top">
    <a href="{% url 'client:home' %}"><img src="{% static 'img/client/logo.png' %}" class="logo"></a>
    <a class="btn btn-default transparent" onclick="openNav()"><span class="glyphicon glyphicon-menu-hamburger glyphicon-lg white transparent"></span></a>
</div>

<form id="fb_details" action="{% url 'client:login' %}" method="post">
    {% csrf_token %}
    <input id="fb_id" type="hidden" name="fb_id">
    <input id="fb_email" type="hidden" name="fb_email">
    <input id="fb_first_name" type="hidden" name="fb_first_name">
    <input id="fb_last_name" type="hidden" name="fb_last_name">
    <input id="facebook" type="hidden" name="facebook" value="facebook" />
</form>

client/templates/client/registration.html
{% extends 'client/base.html' %}
{% load static %}
{% load bootstrap %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/client/forms.css' %}">
<style>
.heading {
  font-family: Open Sans;
  font-weight: 900;
  letter-spacing: 0.05em;
  color: white;
}

{% if facebook %}
.email {
  border-top-left-radius:1em;
  border-top-right-radius:1em;
  padding: 0.5em 1em;
  background-color:white;
}

.password1, .first-name, .last-name {
  padding: 0.5em 1em;
  background-color:white;
}

.password2, .contact-number {
  border-bottom-left-radius:1em;
  border-bottom-right-radius:1em;
  padding: 0.5em 1em;
  background-color:white;
}
{% else %}
.email, .first-name {
  border-top-left-radius:1em;
  border-top-right-radius:1em;
  padding: 0.5em 1em;
  background-color:white;
}

.password1, .last-name {
  padding: 0.5em 1em;
  background-color:white;
}

.password2, .contact-number {
  border-bottom-left-radius:1em;
  border-bottom-right-radius:1em;
  padding: 0.5em 1em;
  background-color:white;
}
{% endif %}

#register {
  padding: 0.75em 1.5em;
}
</style>
{% endblock %}

{% block content %}
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content panel-danger">
      <div class="modal-header panel-heading">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Please fix the following before proceeding:</h4>
      </div>
      <div class="modal-body" style="padding: 25px 50px 25px 50px;">
        <div style="text-align:left;">
          {% if user_form.email.errors %}
          Email Address:
          {{user_form.email.errors}}
          {% endif %}
          {% if user_form.password1.errors or user_form.password2.errors %}
          Password:
          {{user_form.password1.errors}}
          {{user_form.password2.errors}}
          {% endif %}
          {% if client_form.first_name.errors %}
          First Name:
          {{client_form.first_name.errors}}
          {% endif %}
          {% if client_form.last_name.errors %}
          Last Name:
          {{client_form.last_name.errors}}
          {% endif %}
          {% if client_form.contact_number.errors %}
          Contact Number:
          {{client_form.contact_number.errors}}
          {% endif %}
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default btn-xs" data-dismiss="modal">Got it!</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<p class="heading">PLEASE COMPLETE YOUR DETAILS</p>
<form method="post" action="{% url 'client:registration' %}" class="form-horizontal">
    {% csrf_token %}
    <div class="form-input email">
      <label for="id_email" class="control-label">EMAIL ADDRESS</label>
      <input id="id_email" class="form-control" maxlength="254" name="email" type="email" placeholder="juandelacruz@yahoo.com"{% if facebook.email and get %} value="{{ facebook.email }}"{% elif not get %} value="{{ post.email }}"{% endif %} required="">
    </div>
    <hr>
    {% if not facebook %}
    <div class="form-input password1">
      <label for="id_password1" class="control-label">PASSWORD</label>
      <input id="id_password1" class="form-control" name="password1" type="password" required="">
    </div>
    <hr>
    <div class="form-input password2">
      <label for="id_password2" class="control-label">RE-ENTER PASSWORD</label>
      <input id="id_password2"  class="form-control" name="password2" type="password" required="">
    </div>
    <br>
    {% else %}
    <input id="id_password1" maxlength="64" name="password1" type="hidden" value="luckyending">
    <input id="id_password2" maxlength="64" name="password2" type="hidden" value="luckyending">
    {% endif %}
    <div class="form-input first-name">
      <label for="id_first_name" class="control-label">FIRST NAME</label>
      <input id="id_first_name" class="form-control" maxlength="32" name="first_name" type="text" placeholder="Juan" {% if facebook.first_name and get %} value="{{ facebook.first_name }}"{% elif not get %} value="{{ post.first_name }}"{% endif %} required="">
    </div>
    <hr>
    <div class="form-input last-name">
      <label for="id_last_name" class="control-label">LAST NAME</label>
      <input id="id_last_name" class="form-control" maxlength="16" name="last_name" type="text" placeholder="Dela Cruz" {% if facebook.last_name and get %} value="{{ facebook.last_name }}"{% elif not get %} value="{{ post.last_name }}"{% endif %}required="">
    </div>
    <hr>
    <div class="form-input contact-number">
      <label for="id_contact_number" class="control-label">CONTACT NUMBER</label>
      <input id="id_contact_number" class="form-control" name="contact_number" type="text" placeholder="639001234567" {% if not get %}value="{{ post.contact_number }}" {% endif %}required="">
    </div>
    <br>

    <input id="id_username" maxlength="64" name="username" type="hidden" value="user{{facebook.id}}">
    <input id="id_facebook" maxlength="64" name="facebook" type="hidden" value="{% if facebook %}True{% else %}False{% endif %}">

    <input id="fb_id" type="hidden" name="fb_id" value="{{ facebook.id }}">
    <input id="fb_email" type="hidden" name="fb_email" value="{{ facebook.email }}">
    <input id="fb_first_name" type="hidden" name="fb_first_name" value="{{ facebook.first_name }}">
    <input id="fb_last_name" type="hidden" name="fb_last_name"  value="{{ facebook.last_name }}">

    <div align="center">
        <div class="visible-xxs">
          <input type="submit" id="register" class="btn btn-sm orange-button" value="COMPLETE REGISTRATION" style="width:100%"/>
        </div>
        <div class="hidden-xxs visible-xs visible-sm">
          <input type="submit" id="register" class="btn orange-button" value="COMPLETE REGISTRATION" style="width:100%" />
        </div>
        <div class="visible-md visible-lg">
          <input type="submit" id="register" class="btn btn-lg orange-button" value="COMPLETE REGISTRATION" style="width:100%" />
        </div>
        <input type="hidden" name="next" value="{{ next }}" />
    </div>
    <br>
</form>

{% if user_form.errors or client_form.errors %}
<script>
$('#myModal').modal('toggle')
$('#myModal').modal('handleUpdate')
</script>
{% endif %}

{% endblock %}

client/templates/client/transactions.html
transactions.html

{{ transactions }}
<table>
    <thead>
        <tr>
            <td>Created</td>
            <td>Updated</td>
            <td>Client</td>
            <td>Wallet</td>
            <td>Free Credits</td>
            <td>Method</td>
            <td>Type</td>
            <td>Bet?</td>
        </tr>
    </thead>
    <tbody>
        {% for item in transactions %}
        <tr>
            <td>{{ item.created_on }}</td>
            <td>{{ item.updated_on }}</td>
            <td>{{ item.client }}</td>
            <td>{{ item.wallet }}</td>
            <td>{{ item.free_credits }}</td>
            <td>{{ item.get_method_display }}</td>
            <td>{{ item.get_method_type_display }}</td>
            <td>{% for bet in item.bet_set.all %}{{ bet.game }}: {{bet.ending_a}}-{{bet.ending_b}} ({{bet.amount}})<br>{% endfor %}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>