hq/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.home, name="home"),
    url(r'^staff/$', views.staff_activity, name="staff_activity"),
    url(r'^staff/create/$', views.create_staff, name="create_staff"),
    url(r'^games/$', views.games, name="games"),
    url(r'^score/create/$', views.create_score, name="score_game"),
    url(r'^services/credit/$', views.service_credit, name="service_credit"),
]

luckyending/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('client.urls', namespace='client')),
    url(r'^hq/', include('hq.urls', namespace='hq')),
    url(r'^logout/$', logout, name='logout'),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
]

client/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator
from hq.models import Game

# Create your models here.

class Client(models.Model):
    user = models.OneToOneField(User)
    fb_id = models.CharField(max_length=64, blank=True, null=True)
    first_name = models.CharField(max_length=32)
    last_name = models.CharField(max_length=16)
    contact_number = models.CharField(max_length=12)

    def __str__(self):
        return str(self.user.email)

class Transaction(models.Model):
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    client = models.ForeignKey(Client)
    wallet = models.PositiveIntegerField(default=0)
    free_credits = models.PositiveIntegerField(default=0)
    METHOD_CHOICES = (
        ('C', 'Credit'),
        ('D', 'Debit'),
    )
    method = models.CharField(
        max_length=1,
        choices=METHOD_CHOICES,
        default='C',
    )
    METHOD_TYPE_CHOICES = (
        ('SC', 'Service'),
        ('RC', 'Regular'),
        ('GC', 'Game'),
        ('BD', 'Bet'),
        ('CD', 'Cashout')
    )
    method_type = models.CharField(
        max_length=2,
        choices=METHOD_TYPE_CHOICES,
        default='RC',
    )

    def __str__(self):
        s = {'SC': 'SC for Client '+str(self.client.id), 'RC': 'RC for Client '+str(self.client.id), 'GC': 'GC for Client '+str(self.client.id), 'BD': 'Bet/s by Client '+str(self.client.id), 'CD': 'Cashout by Client '+str(self.client.id) }[self.method_type]
        return str(s)

class ServiceCredit(Transaction):
    staff = models.ForeignKey(User, blank=True, null=True)
    SERVICE_TYPE_CHOICES = (
        ('W', 'Welcome Credits'),
        ('P', 'Promo'),
        ('R', 'Referral'),
    )
    service_type = models.CharField(
        max_length=1,
        choices=SERVICE_TYPE_CHOICES,
        default='W',
    )
    details = models.CharField(max_length=64, blank=True, null=True)

class RegularCredit(Transaction):
    SOURCE_CHOICES = (
        ('P', 'Paypal'),
        ('O', 'Others'),
    )
    source = models.CharField(
        max_length=1,
        choices=SOURCE_CHOICES,
        default='W',
    )
    reference = models.CharField(max_length=32)

class GameCredit(Transaction):
    game = models.ForeignKey(Game)
    TRIGGER_CHOICES = (
        ('W', 'Win'),
        ('R', 'Refund'),
    )
    trigger = models.CharField(
        max_length=1,
        choices=TRIGGER_CHOICES,
        default='W',
    )

class Bet(models.Model):
    game = models.ForeignKey(Game)
    client = models.ForeignKey(Client)
    ending_a = models.PositiveIntegerField(validators=[MaxValueValidator(9),])
    ending_b = models.PositiveIntegerField(validators=[MaxValueValidator(9),])
    amount = models.PositiveIntegerField()
    transaction = models.ForeignKey(Transaction, blank=True, null=True)

class Cashout(Transaction):
    STATUS_CHOICES = (
        ('Pe', 'Pending Review'),
        ('Pr', 'Processing'),
        ('Re', 'Released'),
    )
    status = models.CharField(
        max_length=2,
        choices=STATUS_CHOICES,
        default='Pe',
    )
    staff = models.ForeignKey(User, blank=True, null=True)
    reference = models.CharField(max_length=32, blank=True, null=True)
    ACCOUNT_TYPE_CHOICES = (
        ('PPL', 'Paypal'),
        ('BPI', 'BPI'),
        ('BDO', 'BDO'),
    )
    account_type = models.CharField(
        max_length=3,
        choices=ACCOUNT_TYPE_CHOICES,
        default='PPL',
    )
    account_details =models.TextField()

hq/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey

from django.utils import timezone
from datetime import datetime, timedelta

# Create your models here.

class Game(models.Model):
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    action_by = models.ForeignKey(User)
    schedule = models.DateTimeField()
    team_a = models.CharField(max_length=64, blank=True, null=True)
    team_b = models.CharField(max_length=32)
    #status = scored, pending score, open (allow bet), closed (stop bet)

    def __str__(self):
        return self.team_a + " vs " + self.team_b

    def __init__(self, *args, **kwargs):
        super(Game, self).__init__(*args, **kwargs)
        self.__original_schedule = self.schedule
        self.__original_team_a = self.team_a
        self.__original_team_b = self.team_b
        self.changed_from = {'key': 'item'}

    def save(self, *args, **kwargs):
        changed_from = {}
        if self.schedule != self.__original_schedule:
            changed_from['schedule'] = self.__original_schedule
        if self.team_a != self.__original_team_a:
            changed_from['team_a'] = self.__original_team_a
        if self.team_b != self.__original_team_b:
            changed_from['team_b'] = self.__original_team_b

        self.changed_from = changed_from

        super(Game, self).save(*args, **kwargs)
        self.__original_schedule = self.schedule
        self.__original_team_a = self.team_a
        self.__original_team_b = self.team_b

    def status(self):
        delta = self.schedule - timedelta(hours=1) #close 1 hour before
        print("DELTA", delta)
        print("NOW()", timezone.now())
        left = delta - timezone.now()
        days = left.days
        hours = (left.seconds//3600)
        minutes = ((left.seconds//60)%60)
        time = ""
        if days < 100:
            time+="0"
        if days < 10:
            time+="0"
        time+=str(days)+":"
        if hours < 10:
            time+="0"
        time+=str(hours)+":"
        if minutes < 10:
            time+="0"
        time+=str(minutes)
        if timezone.now() < delta:
            return {"description":"OPEN", "days_left":days, "hours_left":hours, "minutes_left":minutes, "time_left":time}
        else:
            return {"description":"CLOSED", "time_left": "000:00:00"}

    def hours_left(self):
        delta = self.schedule - timedelta(hours=1) #close 1 hour before
        print(delta)
        print(timezone.now())
        left = delta - timezone.now()
        print(left)
        if timezone.now() < delta:
            return "OPEN"
        else:
            return "CLOSED"


class Score(models.Model):
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    action_by = models.ForeignKey(User)
    game = models.ForeignKey(Game)
    score_a = models.IntegerField(blank=True, null=True)
    score_b = models.IntegerField(blank=True, null=True)

    class Meta:
        unique_together = ('action_by', 'game')

    def __str__(self):
        return str(self.score_a) + ":" + str(self.score_b) + " (" + str(self.game) + ")"

    def __init__(self, *args, **kwargs):
        super(Score, self).__init__(*args, **kwargs)
        self.__original_score_a = self.score_a
        self.__original_score_b = self.score_b
        self.changed_from = {'key': 'item'}

    def save(self, *args, **kwargs):
        changed_from = {}
        if self.score_a != self.__original_score_a:
            changed_from['score_a'] = self.__original_score_a
        if self.score_b != self.__original_score_b:
            changed_from['score_b'] = self.__original_score_b

        self.changed_from = changed_from

        super(Score, self).save(*args, **kwargs)
        self.__original_score_a = self.score_a
        self.__original_score_b = self.score_b

class StaffActivity(models.Model):
    created_on = models.DateTimeField(auto_now_add=True)
    staff = models.ForeignKey(User)
    content_type = models.ForeignKey(ContentType, related_name="staff_activity")
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    ACTION_CHOICES = (
        ('C', 'Create'),
        ('U', 'Update'),
    )
    action = models.CharField(
        max_length=1,
        choices=ACTION_CHOICES,
        default='C',
    )
    details = models.TextField()

    class Meta:
        verbose_name_plural = 'staff activities'

from django.db.models.signals import post_save
from django.dispatch import receiver

@receiver(post_save, sender=Game)
@receiver(post_save, sender=Score)
def log_post_activity(sender, instance, created, update_fields, **kwargs):
    if created:
        content_type = ContentType.objects.get_for_model(instance)
        details = ""

        if content_type == ContentType.objects.get_for_model(Game):
            details = "[Created game:] " + str(instance)
        elif content_type == ContentType.objects.get_for_model(Score):
            details = "[Updated score:] " + str(instance)

        activity = StaffActivity(staff=instance.action_by, content_type=content_type, object_id = instance.id, content_object=instance, details=details)

        activity.save()

    else:
        content_type = ContentType.objects.get_for_model(instance)
        details = ""

        if content_type == ContentType.objects.get_for_model(Game):
            details = "[Updated game:] " + str(instance)

            changes = ""

            for i, field in enumerate(instance.changed_from):
                if i > 0:
                    changes += "\n"
                changes += "Changed " + field + " from " + str(instance.changed_from[field]) + " to " + str(getattr(instance, field))

        elif content_type == ContentType.objects.get_for_model(Score):
            details = "[Edited score:] " + str(instance)
        
        activity = StaffActivity(staff=instance.action_by, content_type=content_type, object_id = instance.id, content_object=instance, action='U', details=details)

        activity.save()

hq/forms.py
from django import forms
from .models import *
from client.models import *

# from bootstrap3_datetime.widgets import DateTimePicker

class GameForm(forms.ModelForm):
    schedule = forms.DateTimeField(
        input_formats=[
            '%Y-%m-%d %H:%M:%S',    # '2006-10-25 14:30:59'
            '%Y-%m-%d %H:%M',       # '2006-10-25 14:30'
            '%Y-%m-%d',             # '2006-10-25'
            '%m/%d/%Y %H:%M:%S',    # '10/25/2006 14:30:59'
            '%m/%d/%Y %H:%M',       # '10/25/2006 14:30'
            '%m/%d/%Y',             # '10/25/2006'
            '%m/%d/%y %H:%M:%S',    # '10/25/06 14:30:59'
            '%m/%d/%y %H:%M',       # '10/25/06 14:30'
            '%m/%d/%y',             # '10/25/06'
            '%Y/%m/%d %I:%M %p',     # '2006/10/25 2:30 PM'
            '%Y-%m-%d %I:%M %p'     # '2006/10/25 2:30 PM'
        ],
        # widget=DateTimePicker(
        #     options={
        #         "format": "YYYY-MM-DD h:mm a",
        #         "pickSeconds": False
        #     }
        # ),
    )

    class Meta:
        model = Game
        fields = '__all__'

class ScoreForm(forms.ModelForm):
   class Meta:
        model = Score
        fields = '__all__'

class ServiceCreditForm(forms.ModelForm):
    class Meta:
        model = ServiceCredit
        fields = '__all__'

class RegularCreditForm(forms.ModelForm):
    class Meta:
        model = RegularCredit
        fields = '__all__'

class CashoutUpdateForm(forms.ModelForm):
    class Meta:
        model = Cashout
        fields = ('status', 'reference', 'staff')

hq/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User, Group
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse

from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.exceptions import PermissionDenied

from .models import *
from .forms import *

# Create your views here.

def is_admin(user):
    test = user.groups.filter(name='Admin').exists() or user.is_superuser

    if test:
        return True
    else:
        raise PermissionDenied

def is_staff_member(user):
    print(user)
    print(user.groups.filter(name__in=['Staff', 'Admin']).exists())
    test = user.groups.filter(name__in=['Staff', 'Admin']).exists() or user.is_superuser

    if test:
        return True
    else:
        raise PermissionDenied

@login_required(redirect_field_name='next', login_url='client:login')
@user_passes_test(is_admin)
def create_staff(request):
    
    if request.method == 'POST':
        form = UserCreationForm(request.POST)

        if form.is_valid():
            u = form.save()

            u.is_staff = True
            g = Group.objects.all().filter(name='Staff').first()
            u.groups.add(g)

            u.save()

            return HttpResponseRedirect(reverse('client:home'))

    else:
        form = UserCreationForm()

    return render(request, 'hq/staff_create.html', {'form': form})

@login_required(redirect_field_name='next', login_url='client:login')
@user_passes_test(is_admin)
def staff_activity(request):
    
    activities = StaffActivity.objects.all().order_by('-id')

    return render(request, 'hq/staff_activity.html', {'activities': activities})

@login_required(redirect_field_name='next', login_url='client:login')
@user_passes_test(is_staff_member)
def games(request):
    
    games = Game.objects.all().order_by('-id')

    if request.method == 'POST':
        form = GameForm(request.POST)

        if form.is_valid():
            
            game = form.save()
            print(game)
            return HttpResponseRedirect(reverse('hq:games'))

    else:
        form = GameForm()

    return render(request, 'hq/games.html', {'games': games, 'form': form})

@login_required(redirect_field_name='next', login_url='client:login')
@user_passes_test(is_staff_member)
def create_score(request):
    
    if request.method == 'POST':
        form = ScoreForm(request.POST)

        if form.is_valid():
            
            score = form.save()
            return HttpResponseRedirect(reverse('hq:staff_activity'))

    else:
        form = ScoreForm()

    return render(request, 'hq/score_create.html', {'form': form})

@login_required(redirect_field_name='next', login_url='client:login')
@user_passes_test(is_staff_member)
def service_credit(request):
    
    if request.method == 'POST':
        form = ServiceCreditForm(request.POST)

        if form.is_valid():
            
            score = form.save()
            return HttpResponseRedirect(reverse('hq:staff_activity'))

    else:
        form = ServiceCreditForm()

    return render(request, 'hq/service_credit.html', {'form': form})

@login_required(redirect_field_name='next', login_url='client:login')
@user_passes_test(is_staff_member)
def home(request):
    return redirect('hq:games')

hq/templates/hq/base.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        
        <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700" rel="stylesheet"> 
        <style>
        body { margin-top:80px; font-family: 'Open Sans', sans-serif; }
        .navbar-default {
            background-color: #100c0d;
            border-top: 5px solid #f72d00;
            color: #fefefe;
        }
        .navbar-default .navbar-nav>li>a, .navbar-default .navbar-nav>li>a:visited {
            color: #fefefe;
            padding: 30px 20px;
            text-transform: uppercase;
            font-size: 0.85em;
        }
        .navbar-default .navbar-nav>li>a:hover {
            color: #fefefe;
            font-weight: bold;
        }
        .navbar-default .navbar-nav>.active>a, .navbar-default .navbar-nav>.active>a:focus, .navbar-default .navbar-nav>.active>a:hover, .navbar-default .navbar-nav>.open>a, .navbar-default .navbar-nav>.open>a:focus, .navbar-default .navbar-nav>.open>a:hover {
            background: red; /* For browsers that do not support gradients */
            background: -webkit-linear-gradient(#f12f00, #100c0d); /* For Safari 5.1 to 6.0 */
            background: -o-linear-gradient(#f12f00, #100c0d); /* For Opera 11.1 to 12.0 */
            background: -moz-linear-gradient(#f12f00, #100c0d); /* For Firefox 3.6 to 15 */
            background: linear-gradient(#f12f00, #100c0d); /* Standard syntax */
            color: #fefefe;
            font-weight: bold;
        }
        img.logo {
            height: 80px;
            margin-top: -10px;
        }
        .navbar-default .navbar-text {
            margin:0 15px;
            text-transform: uppercase;
            color: #fefefe;
        }

        .btn {
            padding: 0.2em 2em;
            /*margin-left: 10px;
            margin-right: 10px;*/
            margin: 10px 5px;
        }

        .btn-orange {
            background-color: #ea5424;
            color: white;
        }

        .btn-orange:hover {
            color: white;
            font-weight: 600;
        }

        .btn-gray {
            background-color: #979796;
            color: white;
        }

        .btn-gray:hover {
            color: white;
            font-weight: 600;
        }

        </style>
        {% block head %}
        {% endblock %}
    </head>
    <body>
        {% include 'hq/navigation.html' %}
        <br>
        <div class="container">
        {% block content %}
        {% endblock %}
        </div>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        {% block scripts %}
        {% endblock %}
    </body>
</html>

hq/templates/hq/game_create.html
{% extends 'hq/base.html' %}
{% load static %}
{% load bootstrap %}

{% block head %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.44/css/bootstrap-datetimepicker.css">
{% endblock %}

{% block content %}
<form action="{% url 'hq:create_game' %}" method="post">
    {% csrf_token %}
    <!--<div class="form-group" id="schedule_picker">
        <label class="control-label" for="id_schedule">Schedule</label>
        <div class="input-group date">
            <input class="form-control" id="id_schedule" name="schedule" type="text" required="">
            <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
            </span>
        </div>
    </div>-->
    {{ form.schedule|bootstrap }}
    {{ form.team_a|bootstrap }}
    {{ form.team_b|bootstrap }}
    <input class=" form-control" id="id_action_by" name="action_by" type="hidden" value="{{ user.id }}">
    <input type="submit" value="Submit" />
</form>
{% endblock %}

{% block scripts %}
<script src="http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.5.1/moment.min.js"></script>        
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.44/js/bootstrap-datetimepicker.min.js"></script>
<script type="text/javascript">
    $(function () {
        $('#id_schedule').datetimepicker();
    });
</script>
{% endblock %}

hq/templates/hq/games.html
{% extends 'hq/base.html' %}
{% load static %}
{% load bootstrap %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'datatables/datatables.min.css' %}"/>
<link rel="stylesheet" type="text/css" href="{% static 'hq/css/custom-table.css' %}"/>

<style>
body {
    background-color: #e6e7e7;
}
select, input {
    padding: 0.5em 0.5em;
    background-color: #e6e7e7;
}
thead > tr {
    font-weight: 900;
}
.form {
    background-color: #d2d2d2;
    min-height: 70vh;
    padding: 3em 2em;
}

input.form-control {
    padding: 1.5em;
}
input[type="submit"] {
    padding: 0.5em 3em;
    background-color: #ea5424;
}
</style>
{% endblock %}

{% block content %}
<br>
<div class="row">

    <div class="col-md-9">
        <table class="datatable display cell-border">
            <thead>
                <tr>
                    <td>SCHEDULE</td>
                    <!--<td>SCHEDULE</td>-->
                    <td>GAME</td>
                    <td></td>
                </tr>
            </thead>
            <tbody>
            {% for game in games %}
                <tr>
                    <td>{{ game.schedule|date:"Y-m-d H:i" }}</td>
                    <!--<td>{{ game.schedule|date:"r" }}</td>-->
                    <td>{{ game.team_a }} VS {{ game.team_b }}</td>
                    <td>
                        <button class="btn btn-orange">SCORE</button>
                        <button class="btn btn-orange">RESCHED</button>
                        <button class="btn btn-gray">CANCEL</button>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="col-md-3 form">
        <form action="{% url 'hq:games' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label class="control-label  " for="id_schedule">Schedule</label>
                <div class=" ">
                    <input class="form-control" id="id_schedule" name="schedule" type="date" required="">
                </div>    
            </div>
            <br>
            <div class="form-group">            
                <label class="control-label  " for="id_team_a">Team a</label>
                <div class=" ">
                    <input class="form-control" id="id_team_a" maxlength="64" name="team_a" type="text">
                </div>    
            </div>
            <br>
            <div class="form-group">
                <label class="control-label  " for="id_team_b">Team b</label>
                <div class=" ">
                    <input class="form-control" id="id_team_b" maxlength="32" name="team_b" type="text" required="">
                </div> 
            </div>
            <input id="id_action_by" name="action_by" type="hidden" value="{{ user.id }}">
            <br>
            <center><input class="btn btn-orange" type="submit" value="CREATE GAME" /></center>
        </form>
    </div>
    

{% endblock %}

{% block scripts %}
<script type="text/javascript" src="{% static 'datatables/datatables.min.js' %}"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.js"></script>
<script type="text/javascript" src="http://cdn.datatables.net/plug-ins/1.10.15/sorting/datetime-moment.js"></script>
<script>
$(document).ready(function(){
    $('.datatable').DataTable({
        "order": [[ 0, "desc" ]],
        "aoColumnDefs": [
            { 'bSortable': false, 'aTargets': [ 2 ] }
        ],
        "columnDefs": [
            { "type": "datetime-moment", targets: 0 }
        ],
        "aLengthMenu": [[5, 10, 25, -1], [5, 10, 25, "All"]],
        "iDisplayLength": 5,
        responsive: true
    });
});
</script>
{% endblock %}

hq/templates/hq/navigation.html
{% load static %}
{% url 'hq:games' as games %}
{% url 'hq:create_game' as create_game %}
{% url 'hq:score_game' as score_game %}
{% url 'hq:service_credit' as service_credit %}
{% url 'hq:staff_activity' as staff_activity %}
{% url 'hq:create_staff' as create_staff %}
<nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="#"><img src="{% static 'img/client/logo.png' %}" class="logo"></a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="#">Home</a></li>
            <li{% if request.path == games %} class="active"{% endif %}><a href="{% url 'hq:games' %}">View Games</a></li>
            <li{% if request.path == score_game %} class="active"{% endif %}><a href="{% url 'hq:score_game' %}">Score Game</a></li>
            <li{% if request.path == service_credit %} class="active"{% endif %}><a href="{% url 'hq:service_credit' %}">Service Credits</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Staff <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li{% if request.path == staff_activity %} class="active"{% endif %}><a href="{% url 'hq:staff_activity' %}">View Activity</a></li>            
                <li><a href="#">View Service Credits</a></li>
                <li role="separator" class="divider"></li>
                <li class="dropdown-header">Accounts</li>
                <li{% if request.path == create_staff %} class="active"{% endif %}><a href="{% url 'hq:create_staff' %}">Create Staff Account</a></li>
                <li><a href="#">View/Edit Staff Accounts</a></li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><p class="navbar-text">Welcome, {{user}}!</p> <span class="caret"></span></a>
              <ul class="dropdown-menu">           
                <li><a href="#">Logout</a></li>
              </ul>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

hq/templates/hq/score_create.html
{% extends 'hq/base.html' %}
{% load static %}
{% load bootstrap %}

{% block head %}
<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/css/datepicker.min.css">
<script src="http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.5.1/moment.min.js"></script>        
<script src="http://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/3.0.0/js/bootstrap-datetimepicker.min.js"></script>
<script type="text/javascript">
    $(function () {
        $('#schedule_picker').datetimepicker();
    });
</script>
{% endblock %}

{% block content %}
<form action="{% url 'hq:score_game' %}" method="post">
    {% csrf_token %}
    {{ form|bootstrap }}
    <input class=" form-control" id="id_action_by" name="action_by" type="hidden" value="{{ user.id }}">
    <input type="submit" value="Submit" />
</form>
{% endblock %}

hq/templates/hq/service_credit.html
{% extends 'hq/base.html' %}
{% load static %}
{% load bootstrap %}

{% block content %}
<form action="{% url 'hq:service_credit' %}" method="post">
    {% csrf_token %}
    {{ form.client|bootstrap }}
    <div class="form-group">
        <label class="control-label  " for="id_free_credits">Amount</label>
        <div class=" ">
            <input class=" form-control" id="id_free_credits" min="0" name="free_credits" type="number" required="">
        </div>
    </div>
    {{ form.details|bootstrap }}

    <input id="id_wallet" name="wallet" type="hidden" value="0">
    <input id="id_method_type" name="method_type" type="hidden" value="SC">
    <input id="id_staff" name="staff" type="hidden" value="{{ user.id }}">

    <button id="id_service_type" name="service_type" class="button expanded" value="P" type="submit">Grant as Promo</button>
    <button id="id_service_type" name="service_type" class="button expanded" value="R" type="submit">Mark as Referral Bonus</button>
</form>
{% endblock %}

hq/templates/hq/staff_activity.html
{% extends 'hq/base.html' %}

{% block content %}
staff actions

<table>
    <tbody>
    {% for activity in activities %}
        <tr>
            <td>{{ activity.created_on }}</td>
            <td>{{ activity.staff }}</td>
            <td>{{ activity.content_object }}</td>
            <td>{{ activity.details }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

hq/templates/hq/staff_create.html
{% extends 'hq/base.html' %}
{% load static %}
{% load bootstrap %}

{% block content %}

<form action="{% url 'hq:create_staff' %}" method="post">
    {% csrf_token %}
    {{ form|bootstrap }}
    <input type="submit" value="Submit" />
</form>

{% endblock %}